[workspace]
members = [
    "crates/sage",
    "crates/sage-cli",
    "crates/sage-cloudpath",
    "crates/pysage-connector",
]

resolver = "2"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"